// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoCMSR.Server.Data;

#nullable disable

namespace ProyectoCMSR.Server.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiWebCMSR.models.Medicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImagenMedico")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("ProyectoCMSR.Server.models.Articulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ImagenContenido")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ImagenPrincipal")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visitas")
                        .HasColumnType("int");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("ProyectoCMSR.Server.models.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Anestesia General"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Anestesia Pediátrica"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cardiología/Hemodinamista"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Cardiología Pediátrica"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Cirugía Vascular"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Cirugía General"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Cirugía Pediátrica"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Cirugía Maxilofacial"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Dermatología"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Cirugía Facial"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Diabetología"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Endocrinología"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Gastroenterología Pediátrico"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Gastroenterología"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Geriatría"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Gineco-Obstetricia"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Intensivista"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Medicina Interna"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Medicina Familiar"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Neonatología"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Neumología"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Neurología"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Neurocirugía"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Ortopedia"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Traumatología"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Ortopedia Pediátrica"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Otorrinolaringología"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Oftalmología"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Pediatría"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Psiquiatría"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Psicología"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Urología"
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Nefrología"
                        });
                });

            modelBuilder.Entity("ApiWebCMSR.models.Medicos", b =>
                {
                    b.HasOne("ProyectoCMSR.Server.models.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });
#pragma warning restore 612, 618
        }
    }
}
